### ISSUE TITLE
Mention address-like nature of hashnames

### ISSUE THREAD

**Issue by Kagami** [telehash/telehash.org#103]
(Continue discussion started at #86.)

v2 docs mention ([[1]](https://github.com/telehash/telehash.org/blob/master/v2/hashnames.md#hashnames), [[2]](https://github.com/telehash/telehash.org/blob/master/v2/faq.md#simultaneous)) that «applications should treat hashnames as an instance or reachable network address, not as a permanent or portable user identity» but v3 docs miss this information.

Also it would be helpful to provide some channel examples which allow to discovery user identities from the mesh of interconnected hashnames. E.g. multiple resources of the same JID in XMPP.

**Comment by quartzjer** [comment]
The [hashname](https://github.com/telehash/telehash.org/tree/master/v3/hashname) doc has improved this to some degree (could always be better of course).

There's also going to be an XMPP guide created in the coming weeks to address that part (as will other "guides" for other systems).

**Comment by Kagami** [comment]
Thanks, much more clear now.
