### ISSUE TITLE
Update cipher sets browser uses

### ISSUE THREAD

**Issue by Kagami** [telehash/telehash.org#105]
The [Web Cryptography API draft](http://www.w3.org/TR/WebCryptoAPI/) defines enough algorithms so CS2a and CS2b could be implemented in new browsers natively.
It's already available in latest [chromes](https://docs.google.com/document/d/184AgXzLAoUjQjrtNdbimceyXVYzrn3tGpf3xQGCN10g/edit?pli=1) (partly outdated doc) and will arrive in Firefox soon. Other browsers support is [pretty good too](http://caniuse.com/#feat=cryptography) and there are [some](https://github.com/polycrypt/polycrypt) [polyfills](https://github.com/Netflix/NfWebCrypto) also available.

So I think telehash-cs2a could be implemented almost natively and should work pretty fast. (Haven't tested it maturely yet.)

**Comment by quartzjer** [comment]
There's a lot of activity here lately too: https://github.com/crypto-browserify

Also this for cs3a: https://github.com/jedisct1/libsodium.js and/or https://github.com/dchest/tweetnacl-js

**Comment by quartzjer** [comment]
Closing this as it's primarily a telehash-js issue now and will be implemented there using https://github.com/rynomad/subtle
