### ISSUE TITLE
Endpoint Ordering is not clear

### ISSUE THREAD

**Issue by bachp** [telehash/telehash.org#131]
The descriptiuon of [endpoint ordering](https://github.com/telehash/telehash.org/blob/master/v3/e3x/order.md) is not clear.

The following questions remain open from my point of view:
* What pulbic keys are compared? The ones from the choosen cipher?
* The phrase defining the sort order seems a bit complicated. I had to read it several times to be able to understand it correctly.

Further I was also wondering why not just compare the hasname instead of the publickey?

**Comment by quartzjer** [comment]
Good catches, should be more clear.

* the key bytes being compared are the chipher in use (can only be one)
* it's just a binary/bit sort order, high/low
* the e3x context doesn't really care about the whole hashname, somehow it seemed important for it to be a very locally scoped decision at the time?
