### ISSUE TITLE
Add some drawings/diagrams

### ISSUE THREAD

**Issue by bachp** [telehash/telehash.org#133]
I think some parts would benefit from drawings/diagrams to explain certain things.

So I would like to start a discussion on what would be a suitable tool to create these so that everybody can work on the graphic sources.

Some suggestions:
* [asciflow](http://asciiflow.com/) simple ascii based diagrams could be embedded in markdown
* [Pencil Project](http://pencil.evolus.vn/) mostly for gui mockups but also pretty good to draw flowcharts etc. (proprietary .ep file)
* [Libre Office Draw](http://www.libreoffice.org/) allround drawing tool, acceptable for flowcharts (.odg files)
* [SVG (Inkscape, ...](https://inkscape.org/) just graphics, no help for drawing charts

Any other suggestions?

**Comment by quartzjer** [comment]
@temas any thoughts?

**Comment by quartzjer** [comment]
we need more yet, but want to open specific issues for individual diagrams as needed now...
