### ISSUE TITLE
what do branches mean?

### ISSUE THREAD

**Issue by dvanduzer** [telehash/telehash.org#157]
this is really misleading right now: https://github.com/telehash/telehash.org/tree/v3/v3

**Comment by dvanduzer** [comment]
alternatively: that is a backlog from October that is almost complete.

**Comment by quartzjer** [comment]
This is a good view of branch status: https://github.com/telehash/telehash.org/branches

I usually delete stale branches as soon as they're used, but I left v3 around since there were some direct links to it back then, am deleting/cleaning it up now tho, good catch :)
