### ISSUE TITLE
Docs Tweaks

### ISSUE THREAD

**Issue by temas** [telehash/telehash.org#158]
This is a list of tweaks that need to happen so when we render the docs they come out better.  This should be done in the original markdown as much as possible.

- [x] Diagrams
- [x] Code example width

@jer

**Comment by quartzjer** [comment]
I fixed the bad code width in hashname, the rest is just json docs...

Still to-do here off the top of my head:
- [ ] add in stable channels and transports
- [ ] remove tables and implementation listings (don't make sense in spec)
- [ ] TOC

**Comment by bachp** [comment]
@quartzjer What do you mean by: add in stable channels and transports?

**Comment by quartzjer** [comment]
the current spec pdf build doesn't include definitions for any transports (udp, tcp) or channels (path, peer, connect, stream), just needs to include them...

**Comment by temas** [comment]
- [ ] v3/channels/README.md needs some flesh

**Comment by quartzjer** [comment]
just diagrams left @temas ;)
