### ISSUE TITLE
interop meetup tue the 14th?

### ISSUE THREAD

**Issue by quartzjer** [telehash/telehash.org#16]
I figured this is a nice open place to coordinate a meetup for everyone working on switch implementations, @temas @dwaite @stpeter @simmons @dvanduzer @jaytaph @fd @andymuldowney 

I'd love to have a time when we can all be online and do some interop testing between all of our implementations next Tuesday, and since we're pretty geo-diverse it might be best in the morning US-time?

Since there's a contingent of us here in Denver I'd love to try to meet up in person too if people's work-schedules are flexible enough to get an hour or so away, perhaps at galvanize?

My hope is that in the next month we can solidify the current base spec and implementations enough to stamp a 0.9 version (or something more beta-ish) and start to get a wider audience experimenting with it all :)

**Comment by zavg** [comment]
Hi guys! Please feel free to check out new service to hold regular online meetups using Google Hangouts on Air: [webmeetups.net](webmeetups.net).

The service automatically reminds about meetup start in a day and in an hour, deals with time zones, allows you to select active participants and watchers if there are more then 10 attending people. You get rid of Hangouts url and Youtube url copy-pasting, it automatically handles all these things. Also it nicely embeds all YouTube videos in your meetup history.

I am service founder and we just came to production, so I warmly invite you to check out our service. Do not hesitate to ask any questions!
