### ISSUE TITLE
OpenID Connect / JW*

### ISSUE THREAD

**Issue by quartzjer** [telehash/telehash.org#85]
Since telehash provides mesh networking, document how to use the newer OpenID Connect and JWT/JWK/etc standards to facilitate endpoint identity and authorization.

**Comment by bachp** [comment]
Could you elaborate the relation between telehash and OpenID Connect?
I don't immediately see where they should work together?

**Comment by quartzjer** [comment]
Yep, been at the top of my list (after tidying up the chat-v3 refresh), hopefully get a start on that yet today...
