### ISSUE TITLE
Blockchain Support

### ISSUE THREAD

**Issue by quartzjer** [telehash/telehash.org#86]
Document how a telehash mesh can be used to facilitate blockchain-based transactions (both bitcoin/sidechains, and [ethereum](https://www.ethereum.org)). For increasing privacy as a transport, and for adding hashnames to a transaction as a form of authorization/grant for access.

**Comment by quartzjer** [comment]
I'm going to close this issue and use more specific ones like #102 to track these, as well as the draft of the [bitcoin guide](https://github.com/telehash/telehash.org/blob/master/v3/guides/bitcoin.md).

**Comment by ngabo2017** [comment]
I want to ask if Blockchain can be combined with NDN to solve some security issues in the NDN architecture, for example, Interest flooding attack, Signature, and content Privacy, DDoS. Thank You!!
