### ISSUE TITLE
Define the well-known transports

### ISSUE THREAD

**Issue by quartzjer** [telehash/telehash.org#87]
In e3x for wire encoding, discovery semantics, and in paths json.

See mention of path prioritization in #80.

**Comment by jbdatko** [comment]
Question re: discovery. I noticed for v2 there are some [docs](https://github.com/telehash/telehash.org/blob/master/v2/ext/discovery.md) describing discovery, but not for v3.

Is there a built-in discovery mechanism in v3 for hashnames (telehash addresses) or is discovery considered out-of-band?

More generally, this is the classic problem with P2P systems: they usually rely on a centralized or federated system that contains a directory of nodes. After the node is discovered via this mechanism, then P2P communication can take place. I'm just curious how telehash approaches this problem.

**Comment by quartzjer** [comment]
It's definitely an important part of v3 and I didn't realize how missing it is currently, I created #119 to remember to add some docs.

It's a lot simpler in v3 though :)

**Comment by dvanduzer** [comment]
One big change between v2 and v3 is decreasing emphasis on *global* discovery.

The terminology around P2P networks has always been a little sloppy: *content* discovery or *node* discovery? The current generation of BitTorrent supports fully decentralized peer discovery, but that's only useful if you have a content hash. Where do you get a content hash in the first place? Well from Ubuntu's website.

You'd use a private mesh when your Fitbit talks to your Nest, and a public mesh when building a global CDN. The slightly more complicated use case is when your toaster needs to download a weather forecast. It will probably navigate a private mesh to some kind of gateway, which would proxy that query over a public mesh.

**Comment by quartzjer** [comment]
Overall the transport docs have been mildly improved, and discovery is happening in its own issue so I'm closing this one and will use/create other more specific issues per transport as needed.
