### ISSUE TITLE
Extract identity resolution from uri.md

### ISSUE THREAD

**Issue by fd** [telehash/telehash.org#91]
It seems that the [`uri.md` document][uri] describes two separate things:
- resolution of an identity (hashname, keys, paths) using the `canonical`
- provide an easy format (for humans) to pass around routing/contact information for a particular endpoint.

Identity resolution should be pluggable and reusable. `THTP` could use these strategies too (currently the uri.md format is not usable for THTP as it doesn't have the path, query, fragment sections which are necessary for most web apps.)

The list of identity resolution strategies includes (but is not limited to):
- .public
- DNS (SRV/TXT)
- HTTP (`/.well-known/mesh.json`)

Other strategies that could be useful:
- NFC
- QR codes
- etc.

  [uri]: https://github.com/telehash/telehash.org/blob/master/v3/uri.md

**Comment by quartzjer** [comment]
Closing this as URI has been overhauled to be a lot more clear on this front (I hope!).
